[book]
title="crashRT-memo"
authors = ["crashRT"]

language = "ja"
multilingual = false
src = "src"


[output.html]
default-theme = "light"
preferred-dark-theme = "dark"
git-repository-url = "https://github.com/crashRT/tutorial"
git-repository-icon = "fa-github"
edit-url-template = "https://github.com/crashRT/tutorial/edit/main/guide/{path}"